name: Release WakeMyMac

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers tags that match a pattern vX.X.X

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'  # Укажите необходимую версию Xcode

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build binary
        run: |
          xcodebuild -scheme WakeMyMac -configuration Release -derivedDataPath build
          cp build/Build/Products/Release/WakeMyMac .

      - name: Set executable permissions
        run: chmod +x WakeMyMac

      - name: Create tarball
        run: tar -czvf WakeMyMac_${{ env.VERSION }}.tar.gz WakeMyMac

      - name: Calculate SHA256
        id: calculate_sha
        run: echo "SHA256=$(shasum -a 256 WakeMyMac_${{ env.VERSION }}.tar.gz | awk '{print $1}')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: WakeMyMac_${{ env.VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Homebrew Formula
        run: |
          FORMULA_FILE=Formula/wakemymac.rb
          sed -i '' -e "s|url \".*\"|url \"https://github.com/mnmn13/WakeMyMac/releases/download/v${{ env.VERSION }}/WakeMyMac_${{ env.VERSION }}.tar.gz\"|" \
                    -e "s|sha256 \".*\"|sha256 \"${{ env.SHA256 }}\"|" $FORMULA_FILE
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add $FORMULA_FILE
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update wakemymac formula to version v${{ env.VERSION }}"
            git push
          fi
