name: Release WakeMyMac

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers tags that match a pattern vX.X.X

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build binary
        run: |
          xcodebuild -scheme WakeMyMac -configuration Release -derivedDataPath build CODE_SIGNING_ALLOWED=NO
          EXECUTABLE_PATH="/Users/runner/work/WakeMyMac/WakeMyMac/build/Build/Products/Release/WakeMyMac"
          ls build/Build/Products/Release/
          
          cp "$EXECUTABLE_PATH" ./WakeMyMac
      - name: Set executable permissions
        run: chmod +x WakeMyMac

      - name: Create tarball
        run: tar -czvf WakeMyMac_${{ env.VERSION }}.tar.gz WakeMyMac

      - name: Calculate SHA256
        id: calculate_sha
        run: echo "SHA256=$(shasum -a 256 WakeMyMac_${{ env.VERSION }}.tar.gz | awk '{print $1}')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: WakeMyMac_${{ env.VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Update Homebrew Formula
        run: |
          FORMULA_FILE=Formula/wakemymac.rb
          sed -i.bak \
              -e "s|url \".*\"|url \"https://github.com/mnmn13/WakeMyMac/releases/download/v${{ env.VERSION }}/WakeMyMac_${{ env.VERSION }}.tar.gz\"|" \
              -e "s|sha256 \".*\"|sha256 \"${{ env.SHA256 }}\"|" \
              -e "s|version \".*\"|version \"${{ env.VERSION }}\"|" \
              $FORMULA_FILE
          rm ${FORMULA_FILE}.bak
          
          git add $FORMULA_FILE
          
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout main
          git commit -am "Automated report"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
